name: Build Adom.Framework Solution - Unix Platform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET7 environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore Adom.Framework.sln
      - name: Build
        run: dotnet build Adom.Framework.sln --configuration Release --no-restore
